AllCops:
  Exclude: []
  TargetRubyVersion: 2.4.0
Documentation:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/MethodLength:
  Max: 25
Metrics/LineLength:
  Max: 100
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
